### ISSUE TITLE
u64.h not found

### ISSUE THREAD

**Issue by dvtate** [AmamiyaRinyuki/MarisaHttpd#1]
it's needed by libs/sha512.h.
it appears to be local to the project.
this is preventing me from compiling.

**Comment by AmamiyaRinyuki** [comment]
I'll add it, sorry...
2016年4月3日 上午10:49，"Dustin Van Tate Testa" <notifications@github.com>写道：

**Comment by dvtate** [comment]
no need to appologize <3
